- name: Ensure that Jenkins service is stopped
  systemd:
    name: jenkins
    state: stopped
- name: Jenkins Skip startUp for MI
  no_log: false
  lineinfile:
    dest=/etc/default/jenkins
    regexp='^JAVA_ARGS=-Djava.awt.headless=true'
    line='JAVA_ARGS=-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false'
  register: result_skip_startup_wizard
- name: "Creating groovy script directory"
  no_log: false
  file:
    path: "{{ JENKINS_HOME }}/init.groovy.d"
    state: "directory"
    recurse: yes
    owner: jenkins
    group: jenkins
    mode: '0755'
  tags: [ groovy ]
- name: "copy script to mark init setup as complete"
  no_log: false
  changed_when: true
  copy:
    dest: "{{ JENKINS_HOME }}/init.groovy.d/basic-security.groovy"
    src: "files/basic-security.groovy"
    owner: jenkins
    group: jenkins
    mode: '0664'
  notify:
    - 'Start Jenkins'
  tags: [ groovy ]
- meta: flush_handlers      
  tags: [ groovy ]
- name: Wait for Jenkins to start up
  no_log: false
  uri:
    url: http://localhost:8080
    status_code: 200
    timeout: 5
  register: jenkins_service_status
  # Keep trying for 5 mins in 5 sec intervals
  retries: 60
  delay: 5
  until: >
     'status' in jenkins_service_status and
     jenkins_service_status['status'] == 200      
- name: Install ansible plugin on Jenkins
  no_log: false
  jenkins_plugin:
    name: build-pipeline-plugin
  notify:
    - "Restart Jenkins"  
