- name: Ensure that Jenkins service is started
  systemd:
    name: jenkins
    state: stopped
- name: Sleep for 30 seconds for Jenkins service to fully initialize
  ansible.builtin.wait_for:
    timeout: 30
- name: Jenkins Skip startUp for MI
  lineinfile:
    dest=/lib/systemd/system/jenkins.service
    regexp='^Environment="JAVA_OPTS=-Djava.awt.headless=true'
    line='Environment="JAVA_OPTS=-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'    
  register: result_skip_startup_wizard
  no_log: false
  changed_when: true
  notify:
    - "Restart Jenkins"
- meta: flush_handlers      
- name: Sleep for 60 seconds for Jenkins service to fully initialize
  ansible.builtin.wait_for:
    timeout: 60
- name: Install ansible plugin on Jenkins
  no_log: false
  jenkins_plugin:
    name: build-pipeline-plugin
  notify:
    - "Restart Jenkins"  
